config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

myapp/urls.py
# myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.PortalView.as_view(), name='portal'),
    path('compo_form/', views.compo_form, name='compo_form'),
    path('edit_blog_form/', views.edit_blog_form, name='edit_blog_form'),
    path('list/', views.list_data, name='list_data'),
    path('select/', views.select, name='select'),
    path('show_data/', views.show_data, name='show_data'),
]

myapp/models.py
from django.db import models

# myapp/models.py

class Blog(models.Model):
    #title = models.CharField(blank=False, null=False, max_length=150)
    id_num = models.IntegerField(primary_key=True)
    title = models.CharField(blank=True, max_length=150)
    text  = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)
    product = models.CharField(max_length=200, blank=True)
    '''
    def __str__(self):
        return self.title
        #return self.str(id_num)
    '''

class Products(models.Model):
    #id_num = models.IntegerField(primary_key=True, blank=False, null=False)
    product = models.CharField(blank=False, max_length=100)
    #mst_id = models.FloatField(blank=False, null=False)
    mst_id = models.IntegerField()
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)
 
    def __str__(self):
        return self.product

myapp/forms.py
# myapp/forms.py
from django import forms
from django.forms import Form, ModelForm, IntegerField
from django.core.exceptions import ValidationError
from .models import Blog
from .models import Products

data = Products.objects.all()

products = []

for tmp in data:
    products.append(tmp.product)


#def check_product(input, products_list): で使いまわし
def check_name(input_product, products_list):

    list_num = len(products_list)

    for product in products_list:
        if input_product == product:
            break
    else:
        raise ValidationError('\'' + input_product + '\' リストに存在しない製品番号です')

    if input_product == 'hello':
        raise ValidationError('一致した場合のエラーです')

def check_product(value):
    check_name(value, products)

def check_text(value):
    if value == 'world':
        raise ValidationError('一致した場合のエラーです')


class CompoForm(forms.Form):

    '''
    id_num = IntegerField(
            label='ID', required=True
    )
    '''

    # 入力がからの場合はチェックにまわさない
    title = forms.CharField(
        label='タイトル',
        #required=True,
        required=False,
        max_length=150,
        ##validators=[check_product],
        #initial=initial_title,
    )

    text = forms.CharField(
        label='テキスト',
        required=True,
        max_length=500,
        widget=forms.Textarea,
        ##validators=[check_text],
        #initial=initial_text,
    )


class EditBlogForm(forms.Form):

    # 入力がからの場合はチェックにまわさない

    #print("period:1")

    id_num = forms.IntegerField(
            label='ID',
    )

    title = forms.CharField(
        label='タイトル',
        #required=True,
        required=False,
        max_length=150,
        #validators=[check_title],
        ##validators=[check_product],
        #initial=initial_title,
    )
    text = forms.CharField(
        label='テキスト',
        required=True,
        max_length=500,
        widget=forms.Textarea,
        ###validators=[check_text],
        #initial=initial_text,
    )

myapp/views.py
from django.shortcuts import render

# myapp/views.py
from myapp.models import Blog
from myapp.models import Products
from myapp.forms import CompoForm
from myapp.forms import EditBlogForm

from django.template import loader

import pprint

from django.views.generic import TemplateView
from django.db.models import Max


class PortalView(TemplateView):
    template_name = 'myapp/portal.html'


class InputCompoObject:
    def __init__(self):
        ## id最大値取得
        self.id = 0
        self.title = ''
        self.text = ''
    def set_id(self, id):
        self.id = id

## 構成用パラメータ
compo_maxid_object = Blog.objects.aggregate(Max('id_num'))
compo_id =  int(compo_maxid_object['id_num__max'])
input_compo_object_list = []
compo_form_num = 0


def compo_form(request):
    form = CompoForm
    global compo_id
    global compo_form_num
    global input_compo_object_list

    ## 入力値オブジェクト作成
    compo_obj = InputCompoObject()
    compo_obj.set_id(compo_id)

    ## 入力値オブジェクトへインプット関数
    def input_compo_object(form_num, compo_id, title, text):
        input_compo_object_list[form_num].id = compo_id
        input_compo_object_list[form_num].title = form.cleaned_data['title']
        input_compo_object_list[form_num].text = form.cleaned_data['text']

    ## 変数デバッグ用関数
    def debug_var():
        print('form_num =',compo_form_num)
        print('compo_id =',compo_id)
        print('len object_list =',len(input_compo_object_list))
        for o in input_compo_object_list:
            print('object maxid=',o.id)

    print('#68 blog_form実行直後')
    debug_var()

    ## 構成入力画面
    if request.method == 'POST':
        form = CompoForm(request.POST)

        ## プレビューページへ
        if form.is_valid() and ('button_1' in request.POST):
            context = { 'form': form,
                        'compo_num': compo_form_num + 1
                        }
            # object listへobjectを追加
            input_compo_object_list.append(compo_obj)

            compo_id += 1

            ## objectへ入力値インプット
            input_compo_object(compo_form_num, compo_id, form.cleaned_data['title'],form.cleaned_data['title'])

            print('#87 button_1押した時')
            debug_var()

            return render(request, 'myapp/est_preview.html', context = context)

        ## もう一つの構成登録する
        elif form.is_valid() and ('button_2' in request.POST):
            compo_form_num += 1
            print('#100 button_2押した時')
            debug_var()
            context = {
                'form': form,
                'compo_num': compo_form_num + 1
            }

            return render(request, 'myapp/compo_form.html', context = context)


        ## DBに登録してその他製品登録ページへ
        elif form.is_valid() and ('button_3' in request.POST):
            for input_object in input_compo_object_list:
                blog = Blog.objects.create(
                        id_num = input_object.id,
                        title = input_object.title,
                        text = input_object.text,
                )

            # compo object list初期化
            input_compo_object_list = []
            compo_form_num = 0

            print('#135 button_3押した時')
            debug_var()

            return render(request, 'myapp/est_register_ok.html')


        ## リセット
        elif form.is_valid() and ('button_4' in request.POST):
            input_compo_object_list = []
            compo_form_num = 0
            form.title = ''
            form.text = ''

            context = {
                'form': form,
                'compo_num': compo_form_num + 1
            }

            return render(request, 'myapp/compo_form.html', context = context)

    context = {
        'form': form,
        'compo_num': compo_form_num + 1
    }

    return render(request, 'myapp/compo_form.html', context)


def edit_blog_form(request):

    initial_dict = dict(title="TITLE222", text="テキスト")

    form = EditBlogForm(request.GET or None, initial=initial_dict)

    if request.method == 'POST':
        form = EditBlogForm(request.POST)
        if form.is_valid() and ('button_1' in request.POST):
            context = { 'form': form }
            print('button_1')
            return render(request, 'myapp/est_preview.html', context = context)

        elif form.is_valid() and ('button_2' in request.POST):

            ### data 更新時は update(sqlite3)
            blog = Blog.objects.update(
                id_num = form['id_num'].data,
                title = form.cleaned_data['title'],
                text = form.cleaned_data['text'],
            )
 
            return render(request, 'myapp/est_register_ok.html')

    context = {
        'form': form
    }

    return render(request, 'myapp/blog_form.html', dict(form=form))




def list_data(request):

    # dataをリスト表示とデータ選択

    data = Blog.objects.all()
    context = {
            'data': data,
    }

    if request.method == 'POST':
        post_data = request.POST
        post_data_list = list(post_data)
        print('button_value = ', str(post_data_list[1])) #押されたボタンデータ
        print('button_value = ', str(post_data_list[0])) #押されたボタンデータ


        select_id = str(post_data_list[1])
        print("slect_id = ", select_id)

        #押されたボタンデータでデータフィルタ
        select_data = Blog.objects.filter(id_num = select_id)

        id_num = select_data[0].id_num
        title = select_data[0].title
        text = select_data[0].text

        initial_dict = dict(id_num = id_num, title = title, text = text)

        form = EditBlogForm(request.GET or None, initial=initial_dict)

        return render(request, 'myapp/edit_blog_form.html', dict(form=form))

    return render(request, 'myapp/list.html', context)


def select(request):
    
    # ボタン区別テスト

    if request.method == 'POST':
        post_data = request.POST
        print('post_data = ',post_data)

        #print(request.POST["button_1"])

        if 'button_1' in request.POST:
            print("button_1 press!")

            id = 1
            context = data_process(id)

            return render(request, 'myapp/show_data.html', context)

        elif 'button_2' in request.POST:
            #context = { 'id': 2 }

            print("button_2 press!")
        
            id = 2
            context = data_process(id)

            return render(request, 'myapp/show_data.html', context)

    return render(request, 'myapp/select.html')


def show_data(request):

    id = 1

    context = { 'id': id, }

    return render(request, 'myapp/show_data.html', context)

def data_process(id):

    print('data_process!')
    context = {
            'id' : id,
    }

    return context

myapp/templates/myapp/blog_form.html
<form action="{% url 'myapp:blog_form' %}" method="POST">{% csrf_token %}

    <div>構成:{{ compo_num }}</div>
    <br>


    <div>Product:</div>
    <div>{{ form.title }}</div>
        {% if form.errors.title %}
            {% for error in form.errors.title %}
                <div><font color="red">{{ error }}</font></div>
            {% endfor %}
        {% endif %}
   <br>
    <div>text:</div>
    <div>{{ form.text }}</div>
        {% if form.errors.text %}
            {% for error in form.errors.text %}
                <div><font color="red">{{ error }}</font></div>
            {% endfor %}
        {% endif %}
   <br>
    <button type="submit" name="button_1">登録プレビューへ</button>
    <button type="submit" name="button_4">入力リセット</button>
</form>

myapp/templates/myapp/compo_form.html
<form action="{% url 'myapp:compo_form' %}" method="POST">{% csrf_token %}

    <div>構成:{{ compo_num }}</div>
    <br>


    <div>Product:</div>
    <div>{{ form.title }}</div>
        {% if form.errors.title %}
            {% for error in form.errors.title %}
                <div><font color="red">{{ error }}</font></div>
            {% endfor %}
        {% endif %}
   <br>
    <div>text:</div>
    <div>{{ form.text }}</div>
        {% if form.errors.text %}
            {% for error in form.errors.text %}
                <div><font color="red">{{ error }}</font></div>
            {% endfor %}
        {% endif %}
   <br>
    <button type="submit" name="button_1">登録プレビューへ</button>
</form>

myapp/templates/myapp/edit_blog_form.html
<form action="{% url 'myapp:edit_blog_form' %}" method="POST">{% csrf_token %}

    <div>ID:</div>
    <div>{{ form.id_num }}</div>
    <br>


    <div>Product:</div>
    <div>{{ form.title }}</div>
        {% if form.errors.title %}
            {% for error in form.errors.title %}
                <div><font color="red">{{ error }}</font></div>
            {% endfor %}
        {% endif %}
   <br>
    <div>text:</div>
    <div>{{ form.text }}</div>
        {% if form.errors.text %}
            {% for error in form.errors.text %}
                <div><font color="red">{{ error }}</font></div>
            {% endfor %}
        {% endif %}
   <br>
    <button type="submit" name="button_1">確認</button>
</form>

myapp/templates/myapp/est_preview.html
{% for field in form %}
    {{ field.name }}:{{ field.value }}<br>
{% endfor %}


    <div>構成：{{ compo_num }}</div>

<form method="POST" action="">
    {% csrf_token %}
    {% for field in form %}
       {{ field.as_hidden }}
    {% endfor %}
    <input type="submit" name="button_3" value="構成登録終了してその他製品登録">
    <input type="submit" name="button_2" value="別の構成を追加登録">
    <input type="submit" name="button_4" value="内部バッファをすべてリセット">
    <button type="button" onclick="history.back()">戻る</button>
</form>

myapp/templates/myapp/est_register_ok.html
OK!

<p>
<a href='http://10.0.1.5:8080/myapp/'>ポータル</a>
<p>
<a href='http://10.0.1.5:8080/myapp/list/'>データリスト</a>

myapp/templates/myapp/list.html
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Data</th>
            <th>created</th>
            <th>updated</th>
        </tr>
    </thead>
    <tbody>
        {% for object in data %}
        <tr>
            <td>
                    {{ object.id_num }}
            </td>
            <td>
                    {{ object.title }}
            </td>
            <td>
                    {{ object.text }}
            </td>
            <td>
                    {{ object.created_datetime }}
            </td>
            <td>
                    {{ object.updated_datetime }}
            </td>
            <form method="POST">
                {% csrf_token %}
                <td><button type="submit" name={{ object.id_num }}>select</td>
            </form>
        </tr>
        {% endfor %}
    </tbody>
</table>
        <br>
    <p>
    <a href="http://10.0.1.5:8080/myapp/">TOP</a>

myapp/templates/myapp/portal.html
<head>
    <meta charset="utf-8">
    <title>Cache test Django</title>
</head>

<html lang="ja">
<div class="container">
    <body>
        <li><a href="/myapp/compo_form/">compo form</a></li>
        <li><a href="/myapp/edit_blog_form/">edit blog form</a></li>
        <li><a href="/myapp/list/">list</a></li>
        <li><a href="/myapp/select/">select</a></li>
        <li><a href="/myapp/show_data/">show_data</a></li>
    </body>
</div>
</html>

myapp/templates/myapp/select.html
<form method="POST">
    {% csrf_token %}
    <button type="submit" name="button_1" >処理1</button>
    <button type="submit" name="button_2" >処理2</button>
</form>

myapp/templates/myapp/show_data.html
id : {{ id }}